### ISSUE TITLE
implementazioni Tema

### ISSUE THREAD

**Issue by luigipnl** [italia/design-wordpress-theme#10]
Buongiorno, ho difficolta' a comprendere come hai impostato il tema con page builder.
Puoi postarmi la struttura?
non riesco a creare una linearita' come la demo proposta.
Grazie

**Comment by marcogargano** [comment]
Ciao @luigipnl 
ti incollo lo screenshot della mia pagina 

![image](https://user-images.githubusercontent.com/3099816/46921228-f25fbe00-cff8-11e8-9072-d40c13d80d66.png)

Dove c'è la 🔧 puoi impostare colore di sfondo, margini... bisogna dedicarci un attimo di tempo.

**Comment by luigipnl** [comment]
Grazie, era proprio quello che mi necessitava.gentilissimo.

Inviato da Yahoo Mail su Android 
 
  Il dom, 14 ott, 2018 alle 21:38, Marco Gargano<notifications@github.com> ha scritto:   
Ciao @luigipnl
ti incollo lo screenshot della mia pagina



Dove c'è la 🔧 puoi impostare colore di sfondo, margini... bisogna dedicarci un attimo di tempo.

**Comment by GianlucaDiG** [comment]
Salve a tutti, in primis vorrei ringraziare di cuore @marcogargano per il lavoro fatto. Sto testando in queste ore per la prima volta il PageBuilder su un Wordpress caricato in locale. Vedo che c'è un'opzione per importare ed esportare il layout. Saresti così gentile da caricarci il layout come dal tuo sito di esempio?

**Comment by marcogargano** [comment]
@GianlucaDiG grazie mille per i ringraziamenti 😊
e complimenti per l'ottima idea!

Carico qui il file json da importare (è zippato in quanto i json non sono ammessi) 
[home-imported.json.zip](https://github.com/italia/design-wordpress-theme/files/2510282/home-imported.json.zip)

In aggiunta, per ottenere la home come la mia, bisogna impostare la pagina con Modello: Pagina Home e selezionare questa pagina come Home page nel Personalizza > Impostazioni Homepage.
Ti faccio presente anche un eventuale problema legato ai file della Libreria (es. immagini) che non verranno caricate.
