### ISSUE TITLE
caricamento .json

### ISSUE THREAD

**Issue by oscarbadoino** [italia/design-wordpress-theme#12]
hai ami rilevato un problema nel caricamento del .json?
ovvero l'editor mi dice che è pronto per essere inserito, ma quando gli dico d'inserirlo, mi sbatte sulla pagina, ma senza averlo inserito.

**Comment by marcogargano** [comment]
Ciao @oscarbadoino, 
in WordPress vedi i blocchi del Page Builder o non carica proprio niente?

**Comment by oscarbadoino** [comment]
si ma ho sbagliato io nel caricamento. @marcogargano ... in questi giorni ti romperò un po
