### ISSUE TITLE
topbar nera e altre modifiche

### ISSUE THREAD

**Issue by oscarbadoino** [italia/design-wordpress-theme#13]
ciao @marcogargano scusa se ti rompo ma volevo chiederti alcune cose:

- questione menu: togliere le voci da menu topbar nera e in header è possibile? e nel caso come? ( dovrei lasciare una sola voce, e toglierne un paio che sono su di default) idem per il footer

- il colore del "leggi tutto" è modificabile? perché mi sembra che sia il blu "governo" che per alcuni siti di PA minori non sia utilizzabile.

- colori testi e categorie: è possibile cambiare i colori dei "pallini" delle categorie e relativi testi?

ok per ora ho fine di romperti, grazie e scusa

**Comment by marcogargano** [comment]
Ciao  @oscarbadoino 
sono riuscito a vedere quello che mi dicevi, grazie per le segnalazioni ;)
Dunque...
1. se ti riferisci alle voci dei menu, le puoi gestire in Aspetto > Menu
2. ti ringrazio per l'osservazione, faccio in modo di applicargli il colore scelto in Personalizza
3. anche ai pallini farei in modo che prendano il colore del Personalizza

Li inserisco nella prossima release. 😉

**Comment by oscarbadoino** [comment]
grazi @marcogargano 

1. la cosa è diversa ( devo capire anch'io, ma non ho fatto modifiche al tema) ma in pratica quando aggiungo una pagina mi compare in Header e in topbar come da screen allegato.

se hai idee ti sarei grato.
<img width="482" alt="schermata 2019-01-29 alle 09 44 43" src="https://user-images.githubusercontent.com/15978721/51895644-f4346e00-23aa-11e9-9ed4-a3cf00c4596e.png">

**Comment by marcogargano** [comment]
@oscarbadoino verifica che in "Aspetto" > "Menu" > "Impostazioni del menu" (sotto la lista delle voci di menu) non sia selezionato "Aggiungi automaticamente le pagine", deselezionandolo dovresti risolvere.

**Comment by oscarbadoino** [comment]
@marcogargano risolto, in pratica devo attribuire un menu per ogni posizione ( anche vuoto) altrimenti pesca il principale.

**Comment by oscarbadoino** [comment]
@marcogargano perdonami non ho capito alcune cose cosa del nuovo aggiornamento:

- la topbar che era nera ora prende quale colore? ed eventualmente è modificabile?

- idem per il footer

**Comment by marcogargano** [comment]
Ciao @oscarbadoino 
la topbar (quella subito a inizio pagina, per intenderci) ha una tonalità leggermente più scura dello sfondo dell'header. È personalizzabile lo sfondo di tutta la header e la top va di conseguenza.
Idem per il footer.
