### ISSUE TITLE
Data e Categoria

### ISSUE THREAD

**Issue by VSIZElive** [italia/design-wordpress-theme#16]
Ciao Marco,
è possibile abilitare la data di pubblicazione e la categoria di appartenza sia per i widget a orizzontale e articolo a griglia?

**Comment by marcogargano** [comment]
Ciao @VSIZElive , sì certo! 😊
È una cosa che volevo integrare, e dato che devo aggiornare le card ai nuovi layout, credo che rilascerò tutto insieme non appena riesco ad arrivare a uno stato ottimale.
Appena faccio, aggiorno la issue.

**Comment by marcogargano** [comment]
Ciao @VSIZElive 
li ho aggiunti nel widget a grigia.

**Comment by VSIZElive** [comment]
Ciao Marco,
Ottimo !
