### ISSUE TITLE
Visualizzazione "Voci Amministrazione Trasparente" in archive.php e "articoli" in category.php

### ISSUE THREAD

**Issue by lucianoviro** [italia/design-wordpress-theme#17]
Ciao,
sto utilizzando il plugin dell'Amministrazione da te suggerito, ma l'elenco delle "voci" che lui mostra attraverso archive.php non da nulla. Non riesco a venirne a capo.

Ho notato che la stessa cosa capita se voglio visualizzare i post di una categoria ed ho aggiunto a category.php questo:

<?php if ( empty( $category_description ) && have_posts() ) : ?>
                  <?php while ( have_posts() ) : the_post(); ?>
                  <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                  <hr>
                  <?php endwhile; else: ?>

                    <p><?php if(empty( $category_description ) && !have_posts()){_e('Nessun contenuto');} ?></p>
                  <?php endif; ?>

E' capitato anche a voi, come l'avete risolto?

Grazie per il prezioso lavoro fatto!
Ciao
Luciano

**Comment by marcogargano** [comment]
Ciao @lucianoviro 
perdona ma temo di non aver capito, partiamo dall'inizio 😅
Per plugin di Amministazione intendi [Amministrazione trasparente](https://it.wordpress.org/plugins/amministrazione-trasparente/), [Amministrazione aperta](https://wordpress.org/plugins/amministrazione-aperta/), oppure [Page Builder](https://wordpress.org/plugins/siteorigin-panels/) per amministrare WordPress?

**Comment by marcogargano** [comment]
Ciao @lucianoviro 
sinceramente non l'avevo mai provato 😅
L'ho testato al volo e mi sembra funzionare correttamente.
Io ho usato uno shortcode tipo questo nel post: 
`[at-sezioni col="2" bar="2" con="1"] `
e tipo questo nel template: 
`<?php echo do_shortcode('[at-list]') ?>`

Se hai un link da girarmi magari posso esserti più di aiuto.

**Comment by lucianoviro** [comment]
Ciao Marco,
Ok, lo shortcode funziona e l'avevo già inserito in una pagina.
Se inserisco <?php echo do_shortcode('[at-list]') ?> nel template (in 
archive.php) mi mostra nuovamente la lista come con lo shortcode, ma non 
le singole voci.

Il sito è raggiungibile con la modifica Hosts
80.88.87.117 www.comune.cavour.to.it
80.88.87.117 comune.cavour.to.it

Grazie
Luciano




Il 2019-02-15 19:20 Marco Gargano ha scritto:

**Comment by marcogargano** [comment]
Ciao Luciano,
sinceramente non so bene come funzioni questo plugin, secondo me se chiedi direttamente all'autore ti può aiutare più velocemente.
Le uniche info che ho, le ho recuperate [qui](https://www.wpgov.it/servizi/amministrazione-trasparente/), di più non saprei dirti.
