### ISSUE TITLE
versione 0.19 bug o precisionazioni

### ISSUE THREAD

**Issue by oscarbadoino** [italia/design-wordpress-theme#18]
ciao @marcogargano non ho capito se è un problema mio o se ci sono dei bug nell'ultima versione che hai rilasciato. ti metto a seguire le considerazioni:

- [ ] nella visione da utente non loggato se replico gli articoli a griglia il css dello sfondo e la tipografia saltano ( ma da loggato no) ti allego lo screen, ma se vuoi ti mando proprio il link

- [ ] ho visto che da loggato nella barra in alto ( quella sopra leader) c'è un flag a cosa serve?

- [ ] consigli aggiornamento di siteorigin? 

<img width="1189" alt="versione non loggata" src="https://user-images.githubusercontent.com/15978721/52956485-94b8f500-338f-11e9-8b8a-0ab1b9b1f679.png">

<img width="1287" alt="versione loggata" src="https://user-images.githubusercontent.com/15978721/52956486-971b4f00-338f-11e9-860b-136ca13750f4.png">

**Comment by marcogargano** [comment]
Ciao @oscarbadoino 
uno degli ultimi aggiornamenti ha introdotto anche alcune modifiche grafiche, non vorrei ti riferissi a quelle; in pratica ho integrato/aggiornato le card che trovi su [Bootstrap Italia](https://italia.github.io/bootstrap-italia/docs/componenti/card/).
Uno sviluppo futuro che vorrei fare, è integrare la possibilità di attivare l'ombreggiatura.
Per la flag nella barra in alto potresti postare uno screenshot, grazie. 
Siteorigin lo tengo sempre aggiornato e non ho riscontrato problemi.

**Comment by lupo3777** [comment]
Buongiorno Marco, ho visualizzato per caso il sito con il [Samsung Internet Browser](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en) da Samsung Galaxy Tab S3, nella home mancano i contenuti di 4 degli articoli a griglia. Magari sbaglio io qualcosa… su Chrome, Edge e Firefox visualizzo tutto correttamente.
![ps_prestino](https://user-images.githubusercontent.com/47884054/53387486-591dbc80-3987-11e9-8b32-9ab7bed94151.jpg)

**Comment by marcogargano** [comment]
Ciao @lupo3777 
ho scaricato il Samsung Browser e mi sembra funzioni tutto correttamente.
Se mi giri un link, forse potrei capire meglio.

**Comment by lupo3777** [comment]
Ciao Marco, questo è il link della homepage del sito https://www.iccomoprestino.edu.it/ dal tablet gli articoli si leggono come dall'immagine allegata; solo estratto, manca titolo e "leggi di più". Grazie molte

**Comment by marcogargano** [comment]
@lupo3777 
Ok, io avevo provato da smartphone, non avendo un tablet Samsung.
Ho provato a chiedere a un mio amico se stasera riesce a controllare e appena riesco ti faccio sapere.

**Comment by lupo3777** [comment]
Grazie molte Marco. Ho riscontrato che da telefono il menu lingua non funziona come dovrebbe, non nasconde le voci dietro ai tre punti come si vede nella tua demo ma le restituisce subito sotto. Allego un'immagine per chiarire ![menu_lingua](https://user-images.githubusercontent.com/47884054/54470250-d2e5e080-47a4-11e9-97f5-6b6f4d2f71de.jpg). A questo punto non vorrei che sia, unitamente all'altro, un problema di qualche plugin che ho sul sito... posso fare qualcosa per dare una mano? Grazie ancora per il tuo tempo.

**Comment by marcmajan** [comment]
@lupo3777 
Anche io ho riscontrato l’anomalia del menu lingua: ho verificato comunque che accade quando si rinomina il menu stesso. Se rimane col nome di default funziona..

**Comment by lupo3777** [comment]
> @lupo3777
> Anche io ho riscontrato l’anomalia del menu lingua: ho verificato comunque che accade quando si rinomina il menu stesso. Se rimane col nome di default funziona..

Mi dici per piacere come rinominare il menu? Non ricordo più come si chiamava in origine...

**Comment by marcogargano** [comment]
Ciao @marcmajan e @lupo3777 
in effetti è un bug, vedo di sistemarlo il prima possibile.
Grazie per la segnalazione 😉
Il nome di default dovrebbe essere "Lingua"

**Comment by lupo3777** [comment]
perfetto funziona! Grazie grazie

**Comment by marcmajan** [comment]
Ciao Marco
sto utilizzando il tema per il nuovo sito di un istituto superiore, e tutto fila liscio...hai fatto e stai facendo un grande lavoro!
Alcune segnalazioni:
1. Nei devices Apple iOs (ipad, iphone con browser sia Safari che Chrome) la linea che definisce il campo di testo del "Cerca" non appare. Questo può rendere inutilizzabile il modulo da parte di utenti poco esperti.
2. Nella pagina "Articoli" non appare il paginatore, per cui non è possibile accedere ai post eccedenti il numero impostato di visualizzazione per pagina. Viceversa nelle pagine di Archivio per Categorie il paginatore è presente e funzionante.
3. Sarebbe molto opportuno, a mio parere, poter inserire una sidebar alla pagina "Articoli", cosa che, per quanto mi risulta, attualmente non è possibile.

**Comment by marcogargano** [comment]
Ciao @marcmajan ... grazie ☺
Ti rispondo per punti:
1. appena riesco controllo e sistemo
2. ci lavoro e lo inserisco
3. per gli articoli seleziona "Template predefinito"

Grazie mille per le segnalazioni!
Se poi volessi condividermi il tuo sito, ne sarei contento 😉

**Comment by marcmajan** [comment]
Ciao @marcogargano 
il sito che sto ancora costruendo è [https://www.scuolalibrourbino.edu.it](https://www.scuolalibrourbino.edu.it)
Sarebbe utile inserire, oltre al mega menu su cui stai lavorando, anche la possibilità di bloccare dallo scrolling  la barra del menu..

**Comment by marcogargano** [comment]
@marcmajan 
Il menu sticky è tra le cose che integrerò, al momento sto cercando di sviluppare tutto senza js.
Tra l'altro un altro utente aveva installato un plugin che faceva proprio questo e funzionava egregiamente... ho provato a ritrovare il link ma non ricordo più dove mi avesse scritto 😅

**Comment by francescozaia** [comment]
Dovremmo implementare il menu sticky direttamente su Boostrap Italia (non so ancora darti un tempo preciso, visto anche il periodo pasquale): https://github.com/italia/bootstrap-italia/issues/302

**Comment by lupo3777** [comment]
> @lupo3777
> Ok, io avevo provato da smartphone, non avendo un tablet Samsung.
> Ho provato a chiedere a un mio amico se stasera riesce a controllare e appena riesco ti faccio sapere.

Ciao Marco, ora funziona perfettamente. Grazie mille!
