### ISSUE TITLE
Social wall

### ISSUE THREAD

**Issue by petrachigiovanna** [italia/design-wordpress-theme#19]
Salve, sapete se posso installare qualche plug-in che permetta di vedere discussioni social direttamente sul sito?

**Comment by marcogargano** [comment]
Ciao @petrachigiovanna 
per discussioni intendi i commenti nei post oppure un feed social da inserire in una pagina?

**Comment by petrachigiovanna** [comment]
Intendo i commenti nei post

Inviato da iPhone

**Comment by marcogargano** [comment]
@petrachigiovanna 
Ho provato a installare [wpDiscuz](https://wordpress.org/plugins/wpdiscuz/) (che mi sembra una buona soluzione, con buone impostazioni ma con add-ons a pagamento) e non ho riscontrato alcun problema.
Da come è impostato il tema non dovrebbero riscontrarsi problemi con plugin installati, ma se così non fosse segnalamelo.

**Comment by petrachigiovanna** [comment]
Grazie per il consiglio. Mi sembra interessante anche per l'attenzione al GDPR ma mi sono espressa male. Io intendevo un plug-in che mi permettesse di visualizzare nel mio sito i commenti lasciati sui social dagli utenti
