### ISSUE TITLE
Integrazione post social

### ISSUE THREAD

**Issue by petrachigiovanna** [italia/design-wordpress-theme#20]
Salve ho bisogno di integrare sul sito i post già pubblicati su Instagram e Facebook dall'Amministrazione. Per farlo ho usato il plugin "custom-facebook-feed", per cui i post sono visibili in una colonna della home. Sono responsive, hanno lo stesso stile del sito: colori, font, ecc. @marcogargano credi possa andar bene? Hai qualche plugin da consigliarmi anche per Instagram.

Grazie mille per l'attenzione

Giovanna

**Comment by marcogargano** [comment]
Ciao @petrachigiovanna 
il plugin che hai usato è valutato molto bene e se fa quello di cui hai bisogno... ottimo 😁
Mentre per Instagram non saprei, cercherei nella [sezione dei plugin di WordPress](https://it.wordpress.org/plugins/) quello valutato meglio.
