### ISSUE TITLE
Design Bottoni

### ISSUE THREAD

**Issue by emiliano-b** [italia/design-wordpress-theme#23]
Buonasera,
Sto provando a costruire un layout per una homepage ma ho problemi con il design dei bottoni.
Li vorrei senza alcuna icona ma quando li vado a realizzare (anche se la preview è corretta) il risultato è il seguente: 
![Schermata 2019-04-23 alle 17 42 01](https://user-images.githubusercontent.com/49916149/56595959-e8de9080-65ef-11e9-933e-6b091bf8b6fb.png)
ho come un secondo bottone proprio sopra l'esistente.
forse ho saltato qualche passagio, ma come posso risolvere?
grazie anticipatamente
EB

**Comment by marcogargano** [comment]
Ciao @emiliano-b
per inserire i contenuti quale editor stai usando: Gutenberg, SiteOrigin oppure il vecchio TinyMCE?

**Comment by emiliano-b** [comment]
![Schermata 2019-04-24 alle 10 02 39](https://user-images.githubusercontent.com/49916149/56642658-37377200-6678-11e9-8c92-590d2e83d1b0.png)
sto usando i moduli di siteOrigin, per la precisione SiteOriginBotton sono quelli che ho trovato nel template-home.json

**Comment by marcogargano** [comment]
Non mi è mai successa una cosa del genere.
Ma se provassi a creare un nuovo bottone si presenta lo stesso problema?

**Comment by emiliano-b** [comment]
Si esatto. il problema si propone anche con la creazione di un nuovo bottone.
La cosa strana è che nell'anteprima questo problema non si verifica.
Come posso procedere?
![Schermata 2019-04-29 alle 09 56 49](https://user-images.githubusercontent.com/49916149/56882854-2c5c5300-6a65-11e9-8bbf-349cc378df7c.png)

Nel frattempo riprovo a cancellare tutto e reinstallare sia il tema WP che fare di nuovo l'upload del .json
prendo per buoni quelli di questo pacchetto.
attendo tue
grazie

**Comment by marcogargano** [comment]
Proverei a fare un'altra prova in una nuova pagina.
Prova a creare un nuovo bottone da zero in una nuova pagina, non vorrei che il problema sia solo nella homepage.
Altrimenti ti chiederei un link per poter ispezionare questo strano comportamento.

**Comment by emiliano-b** [comment]
Ho provato il una pagina /prova ed effettivamente il bottone si visualizza bene.
volevo usare il vostro .json per avere gia tutti gli standard testuali ecc.
questo è il link http://test.analogie.info/ se vuoi controllare i bottoni.
alla pagina /prova invece c'è il nuovo.
attendo tue e grazie per la disponibilità

**Comment by marcogargano** [comment]
Ho guardato l'html generato ed è come se ci fossero due bottoni, in pratica due href di cui uno vuoto. Non è che hai disattivato e poi riattivato l'editor di SiteOrigin e quindi ha fatto casino.
Proverei a creare una nuova pagina con template Home e riimportare il json.

**Comment by emiliano-b** [comment]
Ho creato una nuova pagina (con template home) ho cancellato la vecchia. Ma il problema si presenta di nuovo. ho fatto >modifica, rimosso l'icona e cambiato il nome ai bottoni. niente di più.
ho anche notato che anche altri bottoni (che non ho toccato per niente) presentano lo stesso problema.
http://test.analogie.info/homepag/
puoi verificare su questo link.
grazie

**Comment by marcogargano** [comment]
Ciao @emiliano-b 
mi è venuto un dubbio e ho verificato la versione di PHP del tuo server.
Se non sbaglio stai usando la versione 5.4.45, non vorrei fosse questo il problema.
WordPress e altri progetti di Design Italia sono orientati alla versione 7; le versioni precedenti sono deprecate e potrebbero aver problemi di sostenibilità e sicurezza. Ti consiglierei di aggiornare la versione del server per non incorrere in ulteriori problemi in futuro.

Mi confermi che stai usando PHP 5?

**Comment by emiliano-b** [comment]
versione attuale: Running PHP version: 5.4.45
e ultima versione di Wordpres.
come posso fare per avere versione php 7?

**Comment by emiliano-b** [comment]
ho aggiornato alla versione 7.2 creato ex novo una pagina e fatto la stessa procedura ma il problema dei pulsanti rimane sempre lo stesso.

**Comment by marcogargano** [comment]
Ho cercato se questo problema si è presentato a qualcun altro e mi sono imbattuto in questo post: 
https://siteorigin.com/thread/duplicated-button-in-karma-theme/

Prova a vedere se la procedura suggerita funziona anche per te 🤞

**Comment by emiliano-b** [comment]
Si ho dato una letta ma non ho altri plug-in attivi quindi non credo ci sia problema di incompatibiltà con altri. ad ogni modo se mi creo una pagina da zero il bottone funziona bene non vorrei che sia il file .json  che possa creare questo issue.
proverò a creare tutta una pagina da zero e se riscontrerò il problema analogo te lo farò presente.
intanto grazie per la tua disponibilità e collaborazione.
EB

**Comment by marcogargano** [comment]
Comunque prova a pulire a fondo la cache di WordPress.
Un plugin, tipo [WP Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/), può aiutarti.

**Comment by emiliano-b** [comment]
Buongiorno,
Ho scaricato il plug-in, ho creato una nuova pagina senza usare il json.
ho creato tutto da zero in modo tale da capire il problema dove fosse.
il widget "DesignItalia-articoli in orizzontale" quando non spunto nessuna voce si vede bene come da espempio
![Schermata 2019-05-06 alle 16 40 35](https://user-images.githubusercontent.com/49916149/57232912-f1868c00-701d-11e9-9ac9-6ce6bc91742a.png) (foto1)
![Schermata 2019-05-06 alle 16 40 42](https://user-images.githubusercontent.com/49916149/57232936-f9463080-701d-11e9-8ae4-6369eb55c87d.png)
(foto 2)
successivamente andando a spuntare le preferenze per il modulo accade di nuovo la stessa cosa dei bottoni:
![Schermata 2019-05-06 alle 16 40 55](https://user-images.githubusercontent.com/49916149/57232962-0bc06a00-701e-11e9-9e8c-35ae3d4c2fd5.png) (foto 3)
![Schermata 2019-05-06 alle 16 41 12](https://user-images.githubusercontent.com/49916149/57232976-111db480-701e-11e9-929e-73682e18d13b.png)
(foto4)
dopo aver cancellato chace ecc come si puo ovviare a questa cosa? è un problema molto serio perchè non mi permette di creare il layout che avevo concordato con il cliente. Mi dispiace ancora insistere ma non riesco a trovare una via di uscita.
attendo tue e grazie per la disponibilità

**Comment by marcogargano** [comment]
@emiliano-b Grazie mille per aver indagato ✌️
Ma, quindi, se non usi il widget "DesignItalia-articoli in orizzontale" funziona tutto correttamente? 
Stasera ricreo la situazione che mi ha esposto e vedo di capire quale possa esser il problema.

**Comment by emiliano-b** [comment]
Se uso il widget funziona salvo però che non spunto le caselle visualizza estratto ecc.
lo stesso anche per gli articoli a griglia.
ho fatto molto prove. alla fine sono riuscito a creare un layout che soddisfi (in parte) le esigenze!
se poi magari c'è qualche operazione da fare dimmi pure!
grazie mille per la cortesia e la disponibilità dismostrata!
buon lavoro!

**Comment by marcogargano** [comment]
Ciao @emiliano-b 
Ho provato a ricreare la situazione che mi hai presentato, ma non sono riuscito a far comparire il problema.
Ti volevo chiedere se puoi ricreare una pagina con la problematica sul tuo sito (tra quelle presenti non l'ho trovata) e inviarmi il link; così provo a capire da lì quale possa esser il problema.

**Comment by emiliano-b** [comment]
certamente,
http://test.analogie.info/prova/
