### ISSUE TITLE
Upload file XLS e altri

### ISSUE THREAD

**Issue by simonezanella** [italia/design-wordpress-theme#24]
Ciao, sto creando il nuovo sito di una scuola insieme ai miei alunni, e ho delle problematiche sull'upload di alcuni tipi di file. Sto utilizzando solo alcuni dei plugin "consigliati" e non ho fatto modifiche particolari al tema. Ricevo errori di sicurezza nel tentativo di caricamento dei file XLS e XLSX (ma non DOC ecc...). Ho provato con plugin e da functions senza successo, sono riuscito solo ad abilitarli temporaneamente usando 
define( 'ALLOW_UNFILTERED_UPLOADS', true );
vi chiedo se c'è qualche configurazione che non ho trovato che li blocca, perchè ho provato anche ad usare 

add_filter('upload_mimes', 'custom_upload_mimes');
function custom_upload_mimes ( $existing_mimes = array() ) {
    $existing_mimes['xlsx'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'; //Adding excel files
	$existing_mimes['xls'] = 'application/vnd.ms-excel';

    return $existing_mimes;
}

ma da comunque errore.
Grazie!

**Comment by marcogargano** [comment]
Ciao @simonezanella 
per la gestione degli allegati io suggerivo [WordPress Download Manager](https://it.wordpress.org/plugins/download-manager/); lo avevo utilizzato e testato, e lo reputo una buona soluzione per raggirare i blocchi del core di WordPress.
Non è richiesto alcun intervento al codice e offre buone possibilità per la gestione di file.
Lo hai provato e ti da problemi?

**Comment by simonezanella** [comment]
Grazie della celere risposta ;)
Wp download manager lo abbiamo provato ma non ci da una resa ottimale per mostrare gli allegati (abbiamo pagine con decine di link di moduli e documenti di scuola) . tendenzialmente non ne avremmo nemmeno bisogno per quello che stiamo facendo ora, la cosa strana che si verifica è che normalmente gli XLS non sono bloccati dal core (ho provato a fare una installazione pulita di default di Wp e infatti li carica), su questa (in cui sono stati messi solo Site Origin e il suo Page Builder e provati, ora disattivati, gli altri plugin consigliati tra cui wp download manager) alcune tipologie di file danno errore nel caricamento (provando con lo stesso su file sull’installazione pulita di Wp invece li carica), per questo cercavo di capire se era stato bloccato da qualche parte nel tema. Un’altra anomalia che ho notato (ma non credo sia collegata, però già che ci siamo...) è che qualsiasi regola inserita nel file style.css del child viene ignorata, come se di nuovo il tema avesse qualcosa che lo blocca. Usiamo l’ultima versione aggiornata e un child theme in cui usiamo solo functions.php e style.css. 🤔

**Comment by simonezanella** [comment]
Ho trovato il problema, avevamo installato TInyMCE Advanced, disattivandolo e reinstallando WordPress da dentro il backup gli upload sono tornati "normali".

**Comment by marcogargano** [comment]
Ottimo 😊
