### ISSUE TITLE
problemi file function

### ISSUE THREAD

**Issue by annaritasiano** [italia/design-wordpress-theme#25]
Ciao Marco,
non lo so se è un problema mio ma ogni volta che cerco di attivare il tema mi compare questa scritta: Fatal error: Can't use function return value in write context in /home/secciravellino/secondocircoloavellino.gov.it/htdocs/wp-content/themes/design-italia/functions.php on line 317
Dove sbaglio?

**Comment by marcogargano** [comment]
Ciao @annaritasiano 
capiamo se può esser legato alla versione di PHP, tu quale versione utilizzi?
