### ISSUE TITLE
Comparsa 'casuale' di pagine e menu

### ISSUE THREAD

**Issue by arturo-dalla-salda** [italia/design-wordpress-theme#27]
Buon pomeriggio.
Collaboro con mia sorella, docente di un Istituto comprensivo e che si occupa per lo stesso della gestione del sito web, che attualmente usa il template ed i moduli di Porte aperte sul web.

Sto facendo dei test per rendere il sito conforme alle disposizioni Agid e sto provando il tema design-italia. I test li sto facendo su una copia del sito già esistente, al fine di valutare l'impatto su ciò che è già stato fatto in passato (ho preferito non fare prove su un sito vuoto perchè sarebbe comunque fonte di rischi importare 6 anni di attività del sito, ovvero circa un migliaio di post e soprattutto un migliaio di atti pubblicati all'albo).

Ho disattivato il plugin per le foto Wp Photo Album Plus che mi dava problemi durante l'installazione. 

Il sito è questo: http://www.istitutocomprensivoiozzelli.gov.it/testdi/

Il tema lo trovo veramente ben fatto ma... mi trovo comparire sparpagliate nell'home page sia tutte le pagine sia tutti i menu non attivi. Mi sono quindi fermato con i test, prima di provare a modificare le pagine (diverse hanno bisogno di ritocchi).

Da cosa potrebbe dipendere?

**Comment by marcogargano** [comment]
Ciao @arturo-dalla-salda
sono contento che il tema ti piaccia 😊
Credo che semplicemente l'homepage come i menù siano da sistemare un pochino. L'import mi sembra sia andato a buon fine; per i menù dovresti abbinare quelli che desideri con quelli disponibili e per la home potresti provare con il json per ottenere un risultato come la demo.
Buon lavoro

**Comment by arturo-dalla-salda** [comment]
Il tema mi piace perché offre già una buona flessibilità nonostante sia ancora “in divenire”.  Ho provato anche due temi che partivano dalla pura integrazione di Wordpress e Bootstrap ma non riuscivo ad ottenere quel che volevo. E non sono abbastanza bravo come programmatore.
Tornando però ai problemi che vengono fuori, il sito attualmente in essere ha cinque aree menu (due nell'header, la colonna destra, la colonna sinistra, il footer) e due particolarità, che non mi interessa replicare, anzi approfitto del passaggio al dominio edu.it per sistemare alcune cose.
La prima particolarità è il consentire di popolare la colonna dei menu sinistra di sottomenu. Quindi avevo tanti sottomenu (es. un sottomenu “Comunicati della presidenza”, uno “Albo – pubblicità legale”, ecc..). 
La seconda è che la colonna di destra si popola delle sottopagine della pagina corrente, per cui per esempio la pagina “Progetti” ha cinque pagine ‘figlie’ (una per ogni area) ognuna delle quali è a sua volta ‘madre’ di altre pagine. 
Appena installato il tema Design Italia mi sono trovato in home page tutti i menu prima ancora di assegnare le posizioni ai soli menu che volevo mostrare, nonché tutte le pagine che erano ‘madri’ di altre con tutte le pagine ‘figlie’. 
Ho sistemato i menu lasciando solo quelli che effettivamente mi servivano e cancellando tutti gli altri. Sono intervenuto su tutte le pagine togliendo il meccanismo genitore-figlio, così che nessuna pagina ha altre pagine madre o figlio. Inoltre ho cambiato tipologia ad una serie di pagine, ovvero quelle che sono agganciate alla pagina ‘normativa’ convertendole in articoli appartenenti ad una categoria specifica, da mostrare quando si apre quella pagina.
Tuttavia il caos rimane. 
Proverò a fare una installazione pulita, con i soli plugin che servono, e poi ad importare gli articoli, per vedere se il problema si risolve.

**Comment by arturo-dalla-salda** [comment]
Buona sera. Ho provato a fare, a questo indirizzo  http://www.istitutocomprensivoiozzelli.gov.it/provadi/  una installazione ex novo di Wordpress (ed esattamente la versione 5.03, visto che il sito di prima era su versione 5.2.1), senza alcun plugin tranne i due di Site Origin, creando una sola pagina ed un solo articolo, creando due menu ma lasciandoli vuoti, e trovo ugualmente tutte le pagine sparpagliate nell'header e nel footer. L'unico modo per evitare che succeda è che non vi siano pagine.
Avevo pensato ad una incompatibilità con la versione di PHP ma si comporta allo stesso modo sia con la versione 5.6.3. (quella con la quale gira il sito 'effettivo), sia con la 7.0 che con la 7.1. ma non cambia nulla.
Non riesco a capire quale sia l'origine del problema, visto che a questo punto non dovrebbe esserci nulla che va in conflitto.....

**Comment by NicolaTeodori** [comment]
Ciao @arturo-dalla-salda,
prova a creare dei menu vuoti e in Aspetto>Menu>Gestione posizioni associali rispettivamente a Lingua Menu, Social Menu e Footer Menu.
E' importante che nessuno abbia il campo "Seleziona Menu"
Buon lavoro

**Comment by arturo-dalla-salda** [comment]
In effetti il problema nasceva proprio da lì. Abitutato ad un tema di cui sfruttavo tutte le posizioni di menu possibili, non avevo pensato a questa evenienza. Creati menu vuoti ed assegnati alle due posizioni (Lingua e Social) che non avevo usato nelle prove, il problema si è risolto. 
A questo punto posso progredire nei miei test :)

**Comment by marcogargano** [comment]
@NicolaTeodori ti ringrazio tantissimo per il supporto! 👍
@arturo-dalla-salda sono contento che abbiate trovato la soluzione.
