### ISSUE TITLE
Escaping delle variabili $_server mancante in entry-di-head.php

### ISSUE THREAD

**Issue by bunglegrind** [italia/design-wordpress-theme#28]
Nel file nel titolo, i link per la condivisione sui social sono prodotti scrivendo sugli href direttamente le variabili $_SERVER['SERVER_NAME'] e $_SERVER['REQUEST_URI'] senza alcun filtro. 

Quelle variabili non devono essere considerate sicure e potrebbero creare delle vulnerabilità.

Meglio che utilizzi le funzioni helper di wordpress per accedere a quei dati con gli opportuni escaping, se del caso.

**Comment by marcogargano** [comment]
Ciao @bunglegrind 
grazie mille per avermeli indicati, devo essermeli dimenticati durante qualche test 👍
Nella prossima release saranno come helper WordPress.
Grazie ancora!
