### ISSUE TITLE
Personalizzare header

### ISSUE THREAD

**Issue by emiliano-b** [italia/design-wordpress-theme#29]
Ciao Marco,
sto finendo di sviluppare il sito che trovi su questo link: test.analogie.info
volevo sapere se era possibile eliminare dall'header l'icona cerca (fastidiosa per mobile) e poi sempre su mobile l'img dell'header (in questo caso logo regione di nespoli) viene come tagliata e quindi non si vede per nulla. Quali soluzioni mi consigli?_
grazie anticipatamente per la dsiponibilità!

**Comment by marcogargano** [comment]
Ciao Emiliano,
questo progetto nasce per creare un tema che rispetti lo sviluppo che stanno portando avanti i ragazzi di Design Italia, il mio riferimento principale è questo: 
https://italia.github.io/bootstrap-italia/docs/esempi/template-comuni-vuoto/
Quindi sto cercando di sviluppare il tema più simile possibile a quello che hanno deciso in Design Italia.
_...non posso comunque vietarti di nascondere il Cerca tramite CSS..._ 😏

Mentre per l'immagine nell'header (quella della regione), hai notato che viene tagliata? 
Mi manderesti uno screenshot, in quanto non pensavo avesse problemi.

Anche in riferimento a questa, le linee guida di Design Italia richiedono che in quello spazio ci sia il riferimento all'organo superiore; quindi nel tuo caso ci andrebbe Regione Umbria.

**Comment by emiliano-b** [comment]
Ciao MArco,
ti allego uno screenshot dell'antepirma in mobile e che poi effettivamente riscontro anche sul mio telefono.
ho fatto la stessa prova usando anche l'immagine suggerita ma il risultato è lo stesso.
![Schermata 2019-06-17 alle 10 20 54](https://user-images.githubusercontent.com/49916149/59589252-cfd2f700-90e9-11e9-9b42-45f018a730e2.png)
attendo tue.

**Comment by marcogargano** [comment]
Emiliano hai trovato un bug: se non si utilizza il menu della lingua si schiaccia tutto.
Ho rilasciato una nuova versione, dovrebbe risolvere il problema.
Il tuo è un utilizzo molto minimal del tema.
Per provare a nascondere il cerca, potresti inserire in "_Aspetto > Personalizza > CSS Aggiuntivo_", il CSS di seguito: 
```
#header .it-search-wrapper {
    display: none;
}
```

Dimmi se funziona, grazie.

**Comment by emiliano-b** [comment]
Ciao Marco,
Il CSS funziona perfettamente, la barra in alto con il logo della regione mi rimane sempre mozzato.
Cosa intendi per utilizzo minimal del tema? ho traslasciato aspetti fondamentali per caso?
altra info: sempre nel aspetto mobile il burger del menu si trova al centro della barra, è possibile invece metterlo nella destra oppure il tema non prevede altre posizioni per il mobile-menu?
grazie ancora.

**Comment by marcogargano** [comment]
Ho rivisto il tuo link e mi sembra che ora il logo in alto rimanga sempre visibile; ho anche notato che hai aggiunto un menu lingua, senza quello non funziona correttamente?

Minimal nel senso che non usi alcune funzionalità (che naturalmente non ti servono), come per esempio il menu della lingua, il widget in home sotto (che anche questo devo sistemare se non utilizzato); un modo di utilizzarlo perfettamente corretto ma che non ho tenuto tanto in considerazione in quando io ho utilizzato tutte le possibilità.

Per il burger, vorrei proprio spostarlo e metterlo di fianco al cerca, ma mi serve tempo 😅
