### ISSUE TITLE
W3C validator

### ISSUE THREAD

**Issue by mcivita** [italia/design-wordpress-theme#3]
Ci sono errori nella validazione con w3c validator.
Ho testato la demo: 
http://design-italia.marcogargano.com/

Non sarebbe il caso di rendere disponibile un tema che sia w3c valido in modo da fornire il pacchetto in regola con la normativa vigente?

**Comment by marcogargano** [comment]
Ciao @mcivita 
grazie mille per aver testato il tema 😁

La demo è un modo per far capire come può diventare un sito che usa questo tema. Ti confesso che lo uso anche per fare test e provare nuove implementazioni 😅
Inoltre facendo un test con quella URL presenta i warning dell'iframe che viene caricato (che cmq ho sistemato 😉).

Ho testato anche la URL dell'istallazione WP e gli errori che ho riscontato sono quelli legati all'inserimento dei contenuti da CMS. 

Se potessi fare un test anche tu appena istallato il tema, sarebbe un ottimo riscontro per me.
Ora siamo in fase di rodaggio e qualunque cosa da sistemare, segnalatemela pure, in modo da rendere milgiore il tema.

Grazie!

**Comment by mcivita** [comment]
Marco perche' non posti anche un demo-content importabile in modo da poter avere gli stessi contenuti della demo e modificarli a piacimento dell'utente?

**Comment by marcogargano** [comment]
@mcivita È un'ottima idea! 
Apro una issue come proposal; dovrò fare una pensata sui contenuti migliori da proporre, devo capire quali saranno le istituzioni che lo useranno... si potrebbero anche fare demo-content differenti... la metto in cantiere 😉

Fammi anche sapere se la validazione di W3C va a buon fine che chiudo questa issue... THX!

**Comment by mcivita** [comment]
Ciao, su una mia installazione di test, con il tuo tema, ho molti warnings e 1 errore:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fangolo-creativo.it%2Fwebscuole%2F

**Comment by marcogargano** [comment]
Ho guardato i risultati, i 2 errori segnalati:
1. quello riferito all'immagine in effetti è una miglioria che posso apportare quando il logo non è caricato
2. è riferito al markup del widget calendar, di cui non ho il controllo

Mentre i warning sono cose "non necessarie" oppure consigliate; ma di queste, dopo averle viste, non me ne preoccuperei.

**Comment by mcivita** [comment]
Ok perfetto. Per il contenuto demo io suggerirei di caricare anche quello che hai già fatto tu nella tua demo. È un ottimo punto di partenza a mio avviso.
Fai un export del tuo contenuto da wordpress c
(Con il tool export integrato) e poi lo posti.
Fattibile? Cosa ne pensi?

**Comment by marcogargano** [comment]
Sì, sì, mi sembra una buona idea. Se riesco nel weekend mi ci metto.

Questa issue la chiudo e passiamo su quella dedicata #4 😉
