### ISSUE TITLE
Inserire icona social 

### ISSUE THREAD

**Issue by SaraSignori** [italia/design-wordpress-theme#30]
Ciao Marco,
vorrei inserire le icone social nel Social menu ma, oltre a poter inserire il link, non mi si presenta la possibilità di inserire l'icona. 
![image](https://user-images.githubusercontent.com/24542756/60791791-a8110500-a164-11e9-843c-14b575880274.png)

Come posso ricreare la struttura presente nel tema demo?
![image](https://user-images.githubusercontent.com/24542756/60791777-a21b2400-a164-11e9-86d7-4c7df6a2586f.png)

Grazie mille in anticipo per il supporto!

Sara

**Comment by marcogargano** [comment]
Ciao @SaraSignori 
al momento ho integrato le icone tramite file css: 
https://cdn.jsdelivr.net/npm/bootstrap-italia@0.14.1/dist/css/italia-icon-font.css 

Nel file CSS trovi le icone a disposizione, richiamabili tramite HTML.
Per esempio, per inserire l’icona di Facebook, dovrai inserire:  
`<i class="it-facebook”></i>`

Le puoi vedere qui: 
https://italia.github.io/design-web-toolkit/components/detail/icons.html
ma ti consigli cmq di verificate che si visualizzino correttamente.

**Comment by SaraSignori** [comment]
Ciao,
ho fatto come dici te e funziona tutto correttamente!!

Grazie

**Comment by marcogargano** [comment]
@SaraSignori ottimo! ✌️

Tra l’altro avevo preparato una Pen per un altro progetto e l’ho riciclata per queste icone; così si visualizzano ed è più semplice sceglierle.
https://codepen.io/marcogargano/full/BgGZbX
Spero ti possa essere di aiuto… buon lavoro!

**Comment by paskuale75** [comment]
Ciao @SaraSignori posso chiederti come accostare la stringa 'seguici' prima delle icone ?

Grazie

**Comment by saras-96** [comment]
Ciao @paskuale75, il progetto finito non prevedeva più le icone a lato della barra di ricerca.
Il cliente ha voluto metterle nel menu in alto a destra (dove se non ricordo male ci andava la select per la lingua). Posso farti vedere come le ho gestite in quel caso, sperando ti possa comunque essere d'aiuto
![image](https://user-images.githubusercontent.com/79454409/115517399-62fd8a80-a287-11eb-8b9c-204824ecddc5.png)


... Eventualmente, hai provato con un :before in css?
