### ISSUE TITLE
Problemi sidebar

### ISSUE THREAD

**Issue by WebmasterAlmerico** [italia/design-wordpress-theme#32]
Selezionando il template con sidebar, nella pagina compare lo spazio ma non i widget inseriti nella sidebar widget area. Questo è accaduto dopo l'ultimo aggiornamento.

**Comment by marcogargano** [comment]
Ciao @WebmasterAlmerico 
il template selezionato dovrebbe essere "Pagina con sidebar" e i widget li hai inseriti in "Page Widget Area"... in pratica quello che succede nella pagina "Contattaci" della demo.
Se hai un link da girarmi posso provare a capire meglio.

**Comment by WebmasterAlmerico** [comment]
Ah! In page widget area! Scusa, ma sidebar widget area a cosa serve?

**Comment by marcogargano** [comment]
È la sidebar dei post.
...in effetti potrei aggiungere Post così si capisce meglio 😅
