### ISSUE TITLE
Widget logiv

### ISSUE THREAD

**Issue by cioccoblocco** [italia/design-wordpress-theme#33]
Ciao @marcogargano, complimenti per il tuo lavoro.
Ho iniziato a provare il tema per il sito della mia scuola.
Utilizzo il plugin Members per creare ruoli specifici (docente, genitore...) e quindi visualizzare l pagine a seconda dell'utente connesso.
Inotre usavo widget-logic come plugin per fare in modo che alcuni widget venissero visualizzati solo da categorie specifiche di utenti.
Ora mi pare che widget login non funzioni con il tuo tema.
Tu consigli di usare custom sidebars, ma mi pare che questo permetta di creare sidebar solo per categorie o specifici autori e non per ruoli, Inoltre riguarda solo le sidebar mentre a me interesserebbero wigdet inserit in righe della pagina come viene costruita con Page Builder.
Altra accorgimento che utilizzavo era usare lo shortcode [members-access] per isolare parti dell pagina e farla visualizzare solo a determinati uoli. Ora inserire lo shortcode in pagine fatte con page-builder è quasi impossibile.
Cosa potrei fare per ottenere quanto desiderato?
ti ringrazio per la tua attenzione

**Comment by marcogargano** [comment]
Ciao @cioccoblocco,
il tema dovrebbe funzionare con qualunque plugin, per verificare che non vada in conflitto con altri plugin ti consiglierei di rimuovere tutti gli altri (compreso Page Builder) e provare solo con quello interessato.
Per capire, il plugin di cui mi parli è quello di seguito?
https://it.wordpress.org/plugins/widget-logic/

Al momento sono in ferie e tornerò operativo a inizio settembre, quindi prima non riuscirò a testarlo.
