### ISSUE TITLE
Update v 0.28 - megamenu (?)

### ISSUE THREAD

**Issue by GianlucaDiG** [italia/design-wordpress-theme#35]
@marcogargano Buongiorno e grazie prima di tutto per il grande lavoro svolto. Ho appena aggiornato il tema alla versione 0.28 e dal changelog leggo "aggiunto megamenu": di cosa stiamo parlando? Grazie e buon lavoro!

**Comment by GianlucaDiG** [comment]
Fantastico! 😍 Sto testando da questa mattina, l'unica questione è che non utilizzo / non credo utilizzerò i titoli delle colonne (per questo progetto nello specifico), quindi per separare le colonne sto rimediando con dei "link personalizzati" con testo `&nbsp;`, target `#` e classe `heading` e necessariamente mi ritrovo degli spazi bianchi extra. Come potrei risolvere? Mi devo inventare qualcosa tipo divisori (`br`, `hr`, ...) o qualche simbolo? Grazie in anticipo!

![screenshot_dev](https://user-images.githubusercontent.com/44399272/64860157-92b8cb00-d62c-11e9-8ef6-12ea8c6badaa.png)
![screenshot_dev2](https://user-images.githubusercontent.com/44399272/64860159-95b3bb80-d62c-11e9-93ac-15bc3359edee.png)

**Comment by marcogargano** [comment]
Ciao @GianlucaDiG 
sono contento che ti piaccia!
Se inserisci semplicemente l'Etichetta di navigazione, senza la classe CSS, compare il link semplice.

**Comment by GianlucaDiG** [comment]
Non ci siamo capiti, io chiedevo un modo per separare le colonne all'interno del megamenu. Ho risolto senza nessuna classe né etichetta mettendo il primo elemento della colonna come "main" e dal secondo elemento in poi come "sottoelemento" del primo elemento. Innaturale, ma funziona.

![screenshot_dev3-01](https://user-images.githubusercontent.com/44399272/65131453-8c956680-d9ff-11e9-8eeb-598dc4db9115.png)

**Comment by marcogargano** [comment]
Le colonne si adattano a seconda della lunghezza delle etichette; se le etichette sono lunghe le colonne iniziano ad andare a capo, altrimenti si posizionano una di fianco all'altra ridimensionandosi.
Comunque se hai trovato una soluzione che ti soddisfa, ben venga  😉👍
