### ISSUE TITLE
oEmbed

### ISSUE THREAD

**Issue by shouri75** [italia/design-wordpress-theme#39]
Buongiorno.
Scrivo per quanto riguarda una problematica relativa all'embed di un post.
Quando incollo il link di un post all'interno di un altro post, grazie alla funzionalità di oEmbed integrata in Wordpress, nel backend mi compare la preview completa del post (titolo, estratto del testo e link al sito di provenienza) mentre nel frontend compare solo il titolo con link.
E' possibile fare in modo che si veda nel frontend esattamente come nel backend?

**Comment by shouri75** [comment]
Forse ho capito il problema: l'url del post originale non è https (mentre il mio sito sì) e questo causa il riconoscimento del link come _mixed content_ che viene quindi "neutralizzato". Se imposto un link di provenienza https il contenuto viene visualizzato correttamente.
Scusami per aver segnalato un problema che non dipende dal tuo tema. Spero possa essere comunque un'informazione utile anche ad altri.

**Comment by marcogargano** [comment]
Ciao @shouri75 
sono contento che tu abbia trovato la soluzione 😅
Avevo provato a riprodurre il caso ma non avevo trovato particolari problemi.
Ormai conviene sempre utilizzare https e diffidare da quelli che non lo utilizzano.
