### ISSUE TITLE
visualizzazione articoli per tag verticale

### ISSUE THREAD

**Issue by rambo1986** [italia/design-wordpress-theme#41]
Ciao, @marcogargano e grazie per il lavoro. 
Ho utilizzato il tuo tema per il sito della scuola dove lavoro e mi trovo piuttosto bene. Avrei bisogno però di sapere come posso fare per visualizzare la lista degli articoli in ordine cronologico orizzontale. 

Utilizzo i tag per visualizzare gli articoli che interessano a docenti, studenti e come puoi vedere [qui](https://www.rosabianca.tn.it/tag/docenti/) vedo gli articoli suddivisi in tre colonne vengono ordinati in verticale. 

Riesci a dirmi in che file vado a modificare questa impostazione per favore? 

Grazie e ancora complimenti

**Comment by PAPPOMN** [comment]
Ciao @rambo1986 ho visto che sei riuscito a fare sul tuo sito a visualizzare la lista articoli in ordine cronologico orizzontale. Mi puoi dire come hai fatto?

Grazie

**Comment by rambo1986** [comment]
> Ciao @rambo1986 ho visto che sei riuscito a fare sul tuo sito a visualizzare la lista articoli in ordine cronologico orizzontale. Mi puoi dire come hai fatto?
> 
> Grazie

Ciao, @PAPPOMN . 
diciamo che ci sono riuscito fino ad un certo punto nel senso che come hai visto semplicemente faccio visualizzare gli articoli su una sola colonna anziché su 3 a prescindere dalla dimensione dello schermo. 

Nel tema sono stati utilizzati delle proprietà css (column-count) che ordinano in quel modo gli articoli e non ho trovato modo di cambiare la cosa senza utilizzare altri metodi e proprietà non avendo le competenze per farlo velocemente. 

Per visualizzare gli articoli su una colonna come ho fatto io basta inserirei nello style.css del tuo tema child o direttamente nei CSS aggiuntivi di wordpress le seguenti condizioni: 

`@media (min-width: 576px) {
.card-columns {
    -webkit-column-count: 1;
    -moz-column-count: 1;
    column-count: 1;
}
}
@media (min-width: 992px) {
.card-columns {
    -webkit-column-count: 1;
    -moz-column-count: 1;
    column-count: 1;
}`

Non sono un esperto quindi non assicuro che sia il modo migliore e più elegante per ottenere il risultato, ma funziona ;-)

chiedi se non sono stato chiaro.
ciao!


``

**Comment by PAPPOMN** [comment]
ok grazie mille

**Comment by marcogargano** [comment]
Ciao,
l'indicazione di @rambo1986 è corretta!
@PAPPOMN per pignoleria lo inserirei così 😃
`@media (min-width: 576px) { 
    .widget_category_mansory .card-columns { 
        -webkit-column-count: 1; 
        -moz-column-count: 1; 
        column-count: 1; 
    }
}`

Grazie a entrambi per il supporto!
