### ISSUE TITLE
Help Icone lingue, e icone social e area personale

### ISSUE THREAD

**Issue by salvatorefe** [italia/design-wordpress-theme#43]
Buon giorno.... vi scrivo per avere un aiuto da parte vostra.
Sto utilizzando il tema per il Comune di Castelvetrano, comune.castelvetrano.tp.it, ma non riesco a capire come inserire le icone della linguae dei social e l'area personale, come si vede nella demo. Ho forse implementato in modo errato il layout?
![FireShot Capture 001 - Tema di WordPress per la Pubblica Amministrazione_ - design-italia marcogargano com](https://user-images.githubusercontent.com/33895185/78130196-1eebdd80-7419-11ea-9f82-f536d5048c6f.png)
Sicuro di un vostro riscontro porgo cordiali saluti

**Comment by marcogargano** [comment]
Ciao @salvatorefe 
nel tema sono presenti due librerie di icone:
- il componente icons del [Web Toolkit](https://italia.github.io/design-web-toolkit/components/detail/icons.html) (che però è stato superato, ma non ti impedisce di usare le icone)
- la libreria Line Awesome by Icons8, di cui trovi delle indicazioni [qui](https://www.marcogargano.com/wp-pa/wp/?p=1809) 

Per entrambi bisognerà incollare il codice html dell'icona nel campo etichetta, per esempio: 
`<i class="it-facebook”></i>` oppure `<i class="lab la-facebook"></i>`

Per le lingue, solitamente il plugin scelto per gestire le lingue (es. Polylang) offre già le bandierine, altrimenti ti suggerirei di usare le emoticons.

Spero ti possa essere di aiuto… buon lavoro!


PS: per il Web Toolkit avevo preparato una Pen così si visualizzano meglio ed è più semplice sceglierle
https://codepen.io/marcogargano/full/BgGZbX

**Comment by salvatorefe** [comment]
Grazie :) E' stato gentilissimo

   Da "Marco Gargano" notifications@github.com
   A "italia/design-wordpress-theme" design-wordpress-theme@noreply.github.com
   Cc "salvatorefe" salvatoreferlito@comune.castelvetrano.tp.it,"Mention" mention@noreply.github.com
   Data Thu, 02 Apr 2020 04:18:26 -0700
   Oggetto Re: [italia/design-wordpress-theme] Help Icone lingue, e icone social e area personale (#43)

   Ciao @salvatorefe
   nel tema sono presenti due librerie di icone:
     * il componente icons del Web Toolkit (che però è stato superato, ma non ti impedisce di usare le icone)
     * la libreria Line Awesome by Icons8, di cui trovi delle indicazioni qui

   Per entrambi bisognerà incollare il codice html dell'icona nel campo etichetta, per esempio:
   <i class="it-facebook”></i> oppure <i class="lab la-facebook"></i>

   Per le lingue, solitamente il plugin scelto per gestire le lingue (es. Polylang) offre già le bandierine, altrimenti ti suggerirei di usare le emoticons.

   Spero ti possa essere di aiuto… buon lavoro!

   PS: per il Web Toolkit avevo preparato una Pen così si visualizzano meglio ed è più semplice sceglierle
   https://codepen.io/marcogargano/full/BgGZbX
