### ISSUE TITLE
nascondere le date delle pagine dai risultati della ricerca

### ISSUE THREAD

**Issue by lupo3777** [italia/design-wordpress-theme#44]
Buongiorno Marco, non ci sentiamo da diverso tempo, mi auguro che tu stia bene.
È possibile nascondere le date delle pagine dai risultati della ricerca?
(es.: https://www.iccomoprestino.edu.it/page/3/?s=libri)
Ti chiedo questo perchè alcuni utenti non colgono la differenza tra le pagine e gli articoli e quando leggono alcune date risalenti al 2011 non capiscono quale link attivare.
Ti ringrazio ad ogni modo e rinnovo i miei complimenti per il bel sito che hai regalato al nostro istituto.

**Comment by marcogargano** [comment]
Ciao @lupo3777 
sono molto contento del vostro sito nuovo 😁

Non c'è una funzionalità da CMS per nasconderle, però potresti inserire il codice CSS che trovi di seguito nella sezione: _Aspetto > Personalizza > CSS aggiuntivo_

```
body.search-results .card .category-top .data {
    display: none;
}
```
Questo nasconderà tutte le date di tutte le card in tutte le pagine di risultato della ricerca.

**Comment by lupo3777** [comment]
> Ciao @lupo3777
> sono molto contento del vostro sito nuovo 😁
> 
> Non c'è una funzionalità da CMS per nasconderle, però potresti inserire il codice CSS che trovi di seguito nella sezione: _Aspetto > Personalizza > CSS aggiuntivo_
> 
> ```
> body.search-results .card .category-top .data {
>     display: none;
> }
> ```
> 
> Questo nasconderà tutte le date di tutte le card in tutte le pagine di risultato della ricerca.

Fantastico come sempre! Grazie grazie.
