### ISSUE TITLE
Immagine in evidenza nelle pagine

### ISSUE THREAD

**Issue by leouzz** [italia/design-wordpress-theme#47]
Buongiorno,
ho notato che impostando una immagine in evidenza nelle pagine questa "sborda" sulla destra,
creando una scroll orizzontale. il problema è visibile anche nella demo alla pagina:
Esempi - Page template - Design Italia Completo.

![image](https://user-images.githubusercontent.com/4449307/80283782-a4ae3080-871a-11ea-8ee6-0deaf24df259.png)

**Comment by marcogargano** [comment]
Ciao @leouzz 
mi sapresti dire OS, browser e versione?
Grazie!

**Comment by leouzz** [comment]
Certamente
Windows 10
Chrome  81.0.4044.122 (ultima versione)
Firefox 75
risoluzione Schermo 1920x1080

**Comment by marcogargano** [comment]
@leouzz grazie ancora per le tue segnalazioni!
Ho capito qual'è il problema, in Win 10 la scrollbar fa parte della viewport (solito Win bug 🤣).
Nella prossima release ci sarà la fix.
Grazie ancora!

**Comment by leouzz** [comment]
grazie a te!

**Comment by marcogargano** [comment]
Ciao @leouzz 
con l'ultima release (v 0.33) dovrei aver fixato il bug segnalato.
Se mi confermi che ora funziona correttamente chiudo questa issue.
Grazie ancora...

**Comment by mikkoart** [comment]
Ciao, ho provato a impostare l'immagine in evidenza in quella che è la mia Home Page, ma non si vede nulla in alto. Vorrei l'effetto copertina nella prima pagina. Sbaglio qualcosa?
