### ISSUE TITLE
Problema Page Builder site origin

### ISSUE THREAD

**Issue by fnecciari** [italia/design-wordpress-theme#48]
Salve Marco,
creando una griglia a tre colonne con page builder di site origin mi ritrovo una colonna per ogni riga

![6a44b173-55ba-415d-9ea8-0c286469d5dd](https://user-images.githubusercontent.com/43566843/84700738-0721f100-af54-11ea-9803-63e23d2f09ef.jpg)

mentre utilizzando un template standard viene visualizzato correttamente

Da cosa può dipendere? È un problema conosciuto?

Grazie

**Comment by GianlucaDiG** [comment]
Stesso problema, risolvo in Gutenberg creando prima le colonne e inserendo poi i blocchi SiteOrigin Widget, sono gli unici che funzionano (con un po' di aggiustamenti sul css). Il PageBuilder di SiteOrigin sul tema design italia non riesco proprio a farlo funzionare, e credo sia un problema di conflitti (?) con il tema stesso.

**Comment by fnecciari** [comment]
Immaginavo, grazie per la conferma Gianluca.

**Comment by GianlucaDiG** [comment]
Di niente! 😉

**Comment by marcogargano** [comment]
Ciao @fnecciari e @GianlucaDiG ! 
Innanzitutto grazie per il supporto reciproco 😊 

Non ho ben capito quando ciò avviene, vi porgo alcune domande per cercare di ricreare il problema: 
- l'editor di default selezionato per post e pagine è Gutenberg o SiteOrigin? 
Nel senso che inserite un blocco di SiteOrign nell'editor Gutenberg o tutto il contenuto è gestito direttamente da SiteOrigin? 
- succede per i post, le pagine o entrambi? 
- il Template selezionato negli Attributi qual è? 

Grazie!

**Comment by fnecciari** [comment]
Ciao @marcogargano, l'editor è Gutenberg, il problema si verificava inserendo il blocco di SiteOrigin nell'editor Gutenberg e succedeva per entrambi. Ho risolto utilizzando un altro Page Builder.
