### ISSUE TITLE
Menù hamburger

### ISSUE THREAD

**Issue by mikkoart** [italia/design-wordpress-theme#49]
Quando entra in gioco il menù hamburger, cliccando su una macro voce non apre la tendina per vedere le sotto voci, ma entra nella pagina corrispondente e sparisce il menù. Puoi vedere qui cosa voglio dire https://www.comune.bruino.to.it/

**Comment by GianlucaDiG** [comment]
Vai in Aspetto->Menu e nelle voci del menu su cui vuoi disabilitare il tag <a> devi inserire nel campo “Classe CSS” la voce “disable”. 

Se non vedi il campo “Classe CSS” devi abilitarlo sempre in Aspetto->Menu quindi apri in alto a destra la tendina “Impostazioni schermata” e metti il tick su “Classi CSS”.

**Comment by mikkoart** [comment]
Grazie mille!
