### ISSUE TITLE
Immagine di copertina

### ISSUE THREAD

**Issue by mikkoart** [italia/design-wordpress-theme#50]
Ciao, non riesco a capire come inserire un'immagine di copertina nella mia Home Page sotto il menù. Ho provato con "immagine in evidenza" e non si vede nulla, nemmeno con altri metodi.

**Comment by marcogargano** [comment]
Ciao @mikkoart 
il template home-page è praticamente vuoto, in modo da dare massima flessibilità nella creazione di questa pagina. 
Ti consiglio di utilizzare le funzionalità di Gutenberg o di un altro builder che preferisci. 
Per esempio, per ottenere l'effetto desiderato, con Gutenberg, puoi inserire: 
_Blocco > Copertina > Larghezza piena_

![Insert-Block-2-1](https://user-images.githubusercontent.com/3099816/85266569-4f6d7180-b474-11ea-9cb0-7d310f9f1641.gif)

**Comment by mikkoart** [comment]
Non so se sbaglio qualcosa, ma non mi consente di utilizzare i Widget di Gutenberg nella Home Page. Non compaiono proprio quando cerco di aggiungere un Widget.

**Comment by mikkoart** [comment]
Mentre nelle altre pagine mi consente di metterla, ma viene dopo il permalink e quindi non si "attacca" all'header.

**Comment by mikkoart** [comment]
Cioè fa questo nelle altre pagine
![immagine](https://user-images.githubusercontent.com/67141804/85372455-27444800-b532-11ea-8d85-eb8c26f9bf26.png)

**Comment by marcogargano** [comment]
La differenza nel template Home è proprio quella, non compare il titolo della pagina ed è vuota (oltre ad avere zone widget dedicate). 
Dato che hai installato Page Builder by SiteOrigin utilizza quello per comporre la pagina, sicuramente hai più possibilità e flessibilità di Gutenberg.
