### ISSUE TITLE
Pulsanti grandi home page

### ISSUE THREAD

**Issue by mikkoart** [italia/design-wordpress-theme#51]
Ciao, vorrei creare nella home page una sorta di area dove inserire dei macro pulsanti per alcuni servizi più ricercati. Una roba tipo quella che c'è nelle foto. Come posso fare? Grazie.

![Senza titolo-1](https://user-images.githubusercontent.com/67141804/85260318-c69e0800-b46a-11ea-9879-d10948c8b8e4.png)
![Senza titolo-2](https://user-images.githubusercontent.com/67141804/85260321-c7cf3500-b46a-11ea-880e-a6658e70b6b0.png)

**Comment by marcogargano** [comment]
@mikkoart , utilizza [Gutenberg](https://wordpress.org/gutenberg/) o un altro builder; io ho consigliato [Page Builder by SiteOrigin](https://it.wordpress.org/plugins/siteorigin-panels/). 
In questo modo puoi inserire tutti gli oggetti di cui hai bisogno.

**Comment by mikkoart** [comment]
Stesso discorso dell'immagine di copertina, non mi consente di utilizzare i Widget di Gutenberg nella Home Page. Non ci sono quando cerco di aggiungerli.

![immagine](https://user-images.githubusercontent.com/67141804/85372851-b9e4e700-b532-11ea-993f-72d7409df3d3.png)

![immagine](https://user-images.githubusercontent.com/67141804/85372869-bfdac800-b532-11ea-963b-debb4e3c3681.png)

**Comment by marcogargano** [comment]
@mikkoart stai usando Page Builder by SiteOrigin e quindi non vedi Gutenberg; in pratica o usi uno o l'altro. 
Comunque va benissimo come stai facendo, usa SiteOrigin Hero! 😉
