### ISSUE TITLE
bug Scroll elenco menù

### ISSUE THREAD

**Issue by mikkoart** [italia/design-wordpress-theme#52]
Ciao, ho visto che hai inserito il blocco della barra superiore quando scrolla la pagina.

Purtroppo, come vedi nella foto, quando scrolli e vai sulla voce di un menù che ha diverse sotto voci, non scrolla più verso il basso l'intero menù, ma bensì la pagina sullo sfondo e di conseguenza le ultime voci del menù a tendina non si vedono (nell'esempio non va sotto Stato Civile). Si può risolvere, p.f.? Lo fa solo da PC, ovviamente da mobile è diverso.

![immagine](https://user-images.githubusercontent.com/67141804/86593762-1e259300-bf96-11ea-92d0-00e41ed07594.png)

**Comment by marcmajan** [comment]
Ciao Marco, ben trovato. Anche io ho notato che l’header sticky non sembra funzionare su iPad, sia con safari che con Chrome...

**Comment by marcogargano** [comment]
Ciao @mikkoart 
purtroppo l'header sticky arriva dalle linee guida di Design Italia. 
A parte condividere questo tipo di comportamento, il mio consiglio è quello di gestire diversamente le voci di menu: l'utente dev'esser guidato nella selezione, quindi ti consiglierei di annidare alcune voci di menu; eventualmente puoi usare il mega-menu integrato nel tema che offre più spazio. 
Inoltre ho notato che lavori su un monitor abbastanza grande, considera anche ci usa piccoli monitor, per esempio uno dei monitor più diffusi rimane il 1366x768 (fonte: [gs.statcounter.com](https://gs.statcounter.com/screen-resolution-stats/desktop/italy)). 

@marcmajan ben trovato anche a te e grazie per il feedback! 
Hai riscontrato qualcosa in particolare? Appena trovo un iPad lo provo, da emulatore non mi dava problemi. 
Nel caso se puoi, allega uno screenshot... grazie mille!

**Comment by mikkoart** [comment]
Va bene @marcogargano però mi dici come non far vedere più i puntini di sospensione sul mega-menù? Ho provato a modificare le classi CSS, ma non riesco a toglierli.

![immagine](https://user-images.githubusercontent.com/67141804/87283741-e79bcb00-c4f5-11ea-8559-71225ebecb4b.png)

**Comment by marcogargano** [comment]
@mikkoart grazie mille per la segnalazione! Su Chrome non comparivano 😅 
Appena riesco, pubblico il fix. 
Intanto puoi incollare la riga di seguito in _Aspetto > Personalizza > CSS aggiuntivo_
```
.menu-main .mega-menu li a { text-overflow: initial; }
```
