### ISSUE TITLE
Multilingua

### ISSUE THREAD

**Issue by cesky84** [italia/design-wordpress-theme#53]
Hai già avuto modo di testare il plugin per il multilingua? Hai un plugin in particolare da suggerire o che hai testato?

**Comment by marcogargano** [comment]
Ciao @cesky84 
io per uno degli ultimi progetti che ho seguito ho usato [Polylang](https://wordpress.org/plugins/polylang/); ha una versione gratuita abbastanza completa, ma non ti nascondo che per alcune cose è un po' macchinoso. 
Altrimenti se hai a disposizione del budget, ti suggerirei [Wpml](https://wpml.org/it/), che ho usato anni fa ed era il più completo.
