### ISSUE TITLE
Menù dispositivi mobili

### ISSUE THREAD

**Issue by vincenzo-72** [italia/design-wordpress-theme#55]
Salve,
ho un problema con il menù sui dispositivi mobili!!!
Cliccando sul link padre non espande e quindi non mostra i link figli.
Ho provato a mettere disable sul genitore ma non succede niente.
Come posso risolvere?

**Comment by marcogargano** [comment]
Ciao @vincenzo-72 
hai qualche indicazione in più per capire quale possa esser il problema? 
La [demo](http://design-italia.marcogargano.com/) ti funziona correttamente?

**Comment by vincenzo-72** [comment]
> Ciao @ vincenzo-72
> hai qualche indicazione in più per capire quale possa essere il problema?
> La [demo](http://design-italia.marcogargano.com/) ti funziona correttamente?

Ciao @marcogargano 
ho scoperto proprio adesso il problema.
Praticamente il funzionamento viene bloccato dai cookie e quindi se si accettano funziona.
