### ISSUE TITLE
Per Marco : un altro footer

### ISSUE THREAD

**Issue by Falconisilvio** [italia/design-wordpress-theme#57]
Le ho inviato una mail con i dettagli 
su un altro tmplate (italiawp2) ho visto un footer particolare 
![footer_italiawp2](https://user-images.githubusercontent.com/70942443/92451743-6c852700-f1bd-11ea-9d36-c75e31c49d52.jpg)
praticamente il suo footer legge i campi creati con un file details.php
esempio
<li>
                                <svg class="icon"><use xlink:href="<?php bloginfo('template_url'); ?>/static/svg/sprite.svg#it-pa"></use></svg>
                                <?php echo __('Address','italiawp2'); ?>
                                <br>
                                <span><?php echo get_option('dettagli-indirizzo'); ?><br>
                                <?php echo get_option('dettagli-cap'); ?>, <?php echo get_option('dettagli-citta'); ?></span>
                            </li>

come potrei usare la stessa cosa nel vostro footer ?

**Comment by marcogargano** [comment]
Ciao @Falconisilvio 
perdona se ti rispondo solo ora... 
Sinceramente non conosco ItaliaWP2 ma posso ipotizzare che siano dei widget nel footer gestibili da CMS. 
Nel mio tema, puoi inserire del testo formattato nel Widget di testo oppure un menu di navigazione.
