### ISSUE TITLE
Componenti

### ISSUE THREAD

**Issue by Sorby** [italia/design-wordpress-theme#6]
Noto con piacere che il progetto del tema WordPress è finalmente partito!

Alcuni spunti:

Sarebbe interessante creare i componenti (https://italia.github.io/bootstrap-italia/docs/componenti/introduzione/) sotto forma di widget, in modo da poterli usare in maniera semplice con il page builder.

Inoltre vedo che il menu di navigazione principale è diverso da quello presente su https://italia.github.io/bootstrap-italia/docs/componenti/navbar/. Per il futuro, imho, penso che potrebbe essere più utile implementare il "megamenu" (quello del web-toolkit), per poter organizzare meglio la vastità dei contenuti presenti nei siti web delle PA con un layout che ne semplifichi la ricerca.

Per quanto riguarda il menu social penso che sia indispensabile l'aggiunta del supporto alle icone, magari utilizzando quelle del web-toolkit https://italia.github.io/design-web-toolkit/components/detail/icons.html.

Mi rendo disponibile per lo svolgimento di eventuali test a riguardo.

**Comment by Sorby** [comment]
Ciao @marcogargano,
ti ringrazio per avermi risposto.

Per quanto riguarda i componenti, mi riferivo più in particolare alla possibilità di integrare card, carousel (magari anche con articoli), dropdown, e altri componenti di Bootstrap Italia (o ancor meglio del Web Toolkit, che ne ha molti altri) con page builder.
Ti parlo da non esperto di page builder, perchè non l'ho mai usato prima, però l'ho trovato molto utile per permettere di "mettere mano" sul sito a chi non conosce l'html, per cui se ci fosse la possibilità di integrare quei componenti con page builder sarebbe fantastico.
Cercando ho trovato questo: https://github.com/siteorigin/docs/blob/develop/widgets-bundle/tutorials/theme-custom-widgets.md

Per farti un esempio concreto: io sono in grado di creare un layout di una pagina mettendo insieme vari componenti lavorando in html, ma diventerebbe una cosa poi ingestibile se qualche "non addetto ai lavori" volesse successivamente anche solo rimuovere un componente dalla pagina.

L'alternativa diventa, altrimenti, la creazione di siti web fatti solamente di pagine testuali e immagini senza qualcosa che aiuti davvero la navigazione. Lo scopo che invece sarebbe bello raggiungere anche usando Wordpress con questo tema, secondo me, sarebbe quello di riuscire a creare qualcosa di simile a [miur.gov.it](http://www.miur.gov.it/), dove l'homepage utilizza tutti (e anche di più) i componenti creati nel web toolkit per creare che semplifichi la UX.

Sicuramente ora ci sono altre priorità, è giusto partire dalle cose più semplici, ma per il futuro sarebbe bello anche approfondire questo aspetto.

**Comment by marcogargano** [comment]
Ciao @Sorby 
ho capito cosa intendi; il mio unico dubbio è dipendere da un Page Builder, però per ora mi sembra la soluzione migliore se un neofita vuole montarsi una pagina carina.
Quindi ho iniziato a customizzare i widget presenti (prova a vedere accordion e tabs) e poi inizio a svilupparne di nuovi... vediamo...
Con l'ultimo rilascio dovrebbero funzionare, fammi sapere se funzionano correttamente 😊
A questo punto però volevo creare la dipendenza dal tema, così quando lo istalli ti suggerisce di installare anche il page builder di SiteOrigin.

**Comment by Sorby** [comment]
Ciao @marcogargano,
ho provato i componenti che mi hai detto, direi che il risultato è ottimo!

Se non vuoi dipendere da Page Builder ma supportarlo "opzionalmente" si potrebbe sviluppare separatamente un plugin che aggiunge gli stili per Page Builder, ma non so quanto sia corretto...

Aggiungere Page Builder come dipendenza del tema, personalmente, non mi sembra una brutta idea: esistono vari temi che fanno affidamento su plugin esterni per la gestione dei contenuti. Poi uno è sempre libero di scegliere se installarlo o meno...

**Comment by marcogargano** [comment]
@Sorby Hai proprio ragione 😀
Stavo valutando di sviluppare i componenti come widget, così li puoi inserire nelle aree widget e te li ritrovi anche nel builder (forse in qualsiasi builder); però quelli più articolati (accordion e tabs) diventa più complicato.

Appena riesco faccio tutto 😅

**Comment by luigipnl** [comment]
Ciao Marco, come mai non vedo le icone di pubblicazione atti del plugin Albo Pretorio?
Succede solo a me?

![immagine](https://user-images.githubusercontent.com/37182420/48299261-0baa3c00-e4cb-11e8-9aa5-8de03f0f4a02.png)
Grazie e complimenti per l'ottimo lavoro

**Comment by marcogargano** [comment]
Ciao @luigipnl grazie mille!
Sinceramente non saprei come aiutarti, non conosco così bene quel plugin.
Prova a rivolgerti direttamente a chi l'ha sviluppato, oppure sulla [pagina di supporto](https://wordpress.org/support/plugin/albo-pretorio-on-line) trovi qualcosa.
