### ISSUE TITLE
Search Form non funziona

### ISSUE THREAD

**Issue by Sachacata** [italia/design-wordpress-theme#64]
Salve, ho un problema con la funzione cerca. Qualsiasi ricerca mi restituisce la pagina notizie (ultimi articoli).
Ho fatto delle prove installando anche search form diversi da quello nativo di wordpress (ajax lite) ma il problema persiste.
Grazie a chi potrà aiutarmi.

**Comment by marcogargano** [comment]
Ciao @Sachacata 
per aiutarti mi puoi dare qualche info in più; per esempio, senza l'utilizzo di alcun plugin, la pagina che ti si apre riporta in fondo alla url "/?s="?

**Comment by Sachacata** [comment]
Grazie Marco, ho scoperto che il problema deriva dal plugin Post List Designer by Category, un plugin che mi permetteva di avere gli articoli in una lista anche in home page e non nella visualizzazione a mosaico, per me molto scomoda. Disattivandolo torna a funzionare il Cerca. Non so se esiste qualche soluzione alternativa...

**Comment by marcogargano** [comment]
Non saprei, non conosco Post List Designer by Category; bisognerebbe indagare nelle sua impostazioni. 
Buon lavoro 😉
