### ISSUE TITLE
Problema Next & Previous Links

### ISSUE THREAD

**Issue by Sachacata** [italia/design-wordpress-theme#65]
Salve, nella pagine degli articoli non compare il link che interrompe gli articoli dopo il numero che imposto in "Impostazioni" "Lettura", "Le pagine del blog visualizzano al massimo".... quindi il notizie precedenti e successive per intenderci. Visualizza tutti gli articoli presenti nel sito senza interruzioni.
Grazie per l'attenzione.

**Comment by marcogargano** [comment]
Ciao @Sachacata 
non so se ho capito bene, tu intendi che non funziona la paginazione negli archivi (categorie, tag, search, ...) e quindi non ti compaiono in fondo i numeri di pagina?

**Comment by Sachacata** [comment]
Esattamente Marco.

**Comment by marcogargano** [comment]
Ciao @Sachacata 
è la prima segnalazione che mi arriva per questo. 
Prima di tutto, se hai plugin attivi, dovresti provare disattivandoli. Inoltre ti volevo chiedere se succede su tutte le pagine di archivio (categorie, tag, anno, ...) o solo in alcune. 
Nella demo online si vede il comportamento che ci si aspetta.

**Comment by Sachacata** [comment]
Ciao, in realtà Marco il problema lo trovavo nella visualizzazione degli articoli, ho anche disattivato tutti plugin ma quando imposto la pagina degli articoli (template->articoli) non vedo la paginazione. Ho risolto con un plugin esterno per ora. Grazie!
