### ISSUE TITLE
Impostazione template predefinito

### ISSUE THREAD

**Issue by LucaDiba** [italia/design-wordpress-theme#67]
Ho cercato (spero) ovunque un'impostazione che permettesse di impostare il template predefinito per le pagine e gli articoli con template "Template predefinito". Non avendo trovato nulla, vorrei chiedere se sia possibile cambiare il template predefinito dall'interfaccia grafica (impostando come predefinito quello custom DI), se sarà possibile farlo in una prossima versione, oppure se (purtroppo) occorra impostare il template per ogni pagina.

Grazie.

**Comment by marcogargano** [comment]
Ciao @LucaDiba 
purtroppo non credo sia possibile, ma non escludo possa esistere un plug-in che lo faccia. 
Altrimenti dovresti creare un tema figlio e modificarlo lato codice.
