### ISSUE TITLE
articoli a griglia in orizzontale?

### ISSUE THREAD

**Issue by odachieti** [italia/design-wordpress-theme#68]
salve,
ringraziandoti infinitamente per il grande lavoro fatto su design italia
una domanda:

nel widget “articoli a griglia” come faccio a mostrare l’ordinamento degli articoli in orizzontale? di default il sistema - a differenza di quello che avviene sui siti PA con design italia - ordina gli articoli in senso verticale e non segue, quindi, un’armonia di lettura orizzontale. E’ possibile modificare questa cosa?

E, infine, come mostrare il resto degli articoli oltre quelli impostati di default?

**Comment by marcogargano** [comment]
Ciao @odachieti 
ti ringrazio per utilizzare il tema. 

Esistono 2 widget: articoli a griglia e articoli in orizzontale. 
Forse il secondo fa al caso tuo; ma ho un dubbio sul fatto di aver capito la domanda: "a griglia" è realizzato come masonry e quindi è pensato per "riempire" gli eventuali buchi nella griglia, per cui la temporalità orizzontale non è detto che venga rispettata. Facendo tutti i box della stessa altezza potresti raggiungere quel risultato.  

Nei widget puoi impostare il numero di articoli da visualizzare.

**Comment by odachieti** [comment]
grazie per la tua risposta :)
vorrei utilizzare il widget "articoli a griglia" - con quello stile esatto - ma con l'ordinamento sull'asse orizzontale (e non verticale come previsto). E' possibile? 

ti allego screenshot per meglio spiegarmi :)

![Schermata 2021-03-02 alle 10 14 44](https://user-images.githubusercontent.com/79651016/109626088-63f42480-7b40-11eb-8568-c19a7d53e5c8.png)

**Comment by marcogargano** [comment]
Ciao @odachieti 
penso di aver capito. 
Io ho riportato quello messo a disposizione da Design Italia, e nel tema non c'è un'impostazione per gestire l'ordine in quel senso. Però si può inserire una parte di CSS per ottenere quel risultato. 
Sapresti come aggiungere del CSS addizionale in Wordpress?

**Comment by odachieti** [comment]
si certo! te ne sarei davvero grato.. anche perchè su alcuni siti PA ho visto che hanno ordinamento orizzontale. Forse non tutti. Ma sarebbe davvero apprezzato se potessi darci questa dritta

**Comment by marcogargano** [comment]
Ciao @odachieti 
prova a inserire le righe di CSS di seguito in "_Personalizza > CSS aggiuntivo_". 
Considera che ho aggiunto un'altezza minima altrimenti si creano dei buchi; se il contenuto dovesse aver bisogno di più spazio, si allunga ma temo per i buchi. 
Prova a vedere come si comporta sul tuo sito e se soddisfa la tua richiesta, al massimo si può modificare. 

```
.card-columns {
    column-count: auto;
    text-align: center;
}
.card-columns > .card {
    max-width: 360px;
    margin: 14px;
    min-height: 400px;
    width: 100%;
    text-align: left;
    vertical-align: top;
}
```

**Comment by marcogargano** [comment]
Ciao @odachieti 
prova a sostituire con questo: 

```
.card-columns {
    column-count: auto !important;
    text-align: center;
}
.card-columns > .card {
    min-width: 290px;
    max-width: 100%;
    margin: 1% !important;
    min-height: 400px;
    width: 31% !important;
    text-align: left;
    vertical-align: top;
}

@media screen and (max-width: 575px) {
    .card-columns > .card {
        min-width: 100%;
        min-height: auto;
	}
}
```

**Comment by odachieti** [comment]
grande Marco! funziona :-)
ho visto che ci sono altri post che chiedevano questa modifica... forse va messo in evidenza.
un caro saluto e grazie per tutto il lavoro che fai!
