### ISSUE TITLE
eliminazione link di navigazione tra articoli

### ISSUE THREAD

**Issue by angelavit** [italia/design-wordpress-theme#69]
Ciao,
vorrei sapere se è possibile eliminare i link ad articolo precedente e successivo, che compaiono in calce all'articolo che si sta visualizzando
grazie

**Comment by marcogargano** [comment]
Ciao @angelavit 
tramite CMS non è previsto. 
Potresti creare un tema figlio o nasconderlo tramite CSS.

**Comment by angelavit** [comment]
grazie
