### ISSUE TITLE
Informazioni

### ISSUE THREAD

**Issue by Dani6789** [italia/design-wordpress-theme#71]
Inizio complimentandomi con lei @marcogargano per il tema che ha creato, è davvero utilissimo e ben fatto. Io l'ho scelto per la realizzazione del sito web della Protezione Civile comunale (per la quale sono anche volontario) e sino ad ora mi sto trovando bene soprattutto per la flessibilità e l'intuitività con cui si riesce a lavorare materialmente.

Chiedo con questo post se esista un **plugin specifico per creare una pagina gallery** e **come creare un pagina archivio notizie.**

**Comment by marcogargano** [comment]
Ciao @Dani6789 
grazie mille per i complimenti 😊

Per la pagina gallery, l'editor di WordPress fornisce una [semplice gallery](https://gogutenberg.com/blocks/gallery/), altrimenti se hai installato SiteOrigin Page Builder e il Widgets Bundle puoi utilizzare lo [Slider Widget](https://siteorigin.com/widgets-bundle/slider-widget-documentation/). 
Plugin per creare gallery ne esistono tanti, dipende dalla propria necessità (slider, lightbox, ...). 

Invece per la pagina archivio delle notizie, WordPress prevede già archivi per categoria, tag, e temporale. Per esigenze diverse si possono utilizzare diversi plugin, anche qui dipende dalle proprie esigenze.

**Comment by Dani6789** [comment]
Grazie per le informazioni. Chiedo un'ultima informazione, come faccio per personalizzare l'header?

**Comment by marcogargano** [comment]
Le personalizzazioni previste dal tema le puoi trovare nella sezione dedicata: Aspetto > Temi > Personalizza 
Altrimenti puoi personalizzare ciò che desideri creando un tema figlio.
