### ISSUE TITLE
errori di contrasto

### ISSUE THREAD

**Issue by mikygo123** [italia/design-wordpress-theme#73]
Buongiorno,
innanzitutto complimenti per il tema, pulito, lineare e nello stesso tempo molto bello @marcogargano.
Ho scaricato il tema per un istituto a cui stiamo sviluppando il sito. Ho creato un tema figlio e importato il json della homepage. Ora il sito è su un dominio che non è definitivo (dev.example.it e non www.example.it). Sto riscontrando un errore sui contrasti utilizzando https://webaim.org/resources/contrastchecker/. I colori sono il blu e testo bianco nel header e nel body il testo è nero e i link blu. E' come se il validatore recepisse i link azzurri sull'header blu e quindi mi dà una serie di errori di contrasto non rispettato. Cosa sto sbagliando? Grazie . Cordiali saluti

**Comment by marcogargano** [comment]
Ciao @mikygo123 
grazie per i complimenti e per utilizzare il tema. 
Validatori di questo tipo ne esistono tanti e secondo me devo comunque esser riscontrati. 
Gli errori che presentano dovrebbero esser verificati ed eventualmente corretti; ma capita anche che l'indicazione non è puntuale e quindi verificando ti rendi conto che il feedback del validatore non è corretto. 

Questo validatore in particolare non lo conoscevo, l'ho provato e mi ha dato diversi errori, alcuni che non mi tornano molto. 
Potresti provare con altri validatori e fare delle considerazioni; il contributo umano in queste analisi, secondo me, è molto importante.

**Comment by mikygo123** [comment]
Grazie per la risposta. Di solito che tool viene consigliato di utilizzare? Questo fa parte di un'estensione di Chrome.

**Comment by marcogargano** [comment]
Il tool che io preferisco è l'inspector di Chrome, ma anche W3C fa degli ottimi tool. 
Però il risultato che viene generato in automatico, secondo me, dev'esser sempre verificato e riscontrato.
