### ISSUE TITLE
Custom post type nei widget - Proposta 

### ISSUE THREAD

**Issue by Alliance8791** [italia/design-wordpress-theme#75]
Ciao, volevo chiedere se per i due ottimi widget "DesignItalia - Articoli a griglia" e "DesignItalia - Articoli in orizzontale" si potesse aggiungere la ricerca anche tra i custom post type oltre che per le sole categorie.
Grazie

**Comment by marcogargano** [comment]
Ciao @Alliance8791 
al momento non è previsto; per estendere il comportamento dei widget, ti consiglierei di creare un tema figlio e implementare questa logica. 
Grazie a te!
