### ISSUE TITLE
Visualizzazione Social menu da Mobile

### ISSUE THREAD

**Issue by angelavit** [italia/design-wordpress-theme#76]
Ciao,
è possibile visualizzare il menu social da dispositivo mobile?
grazie
Ciao

**Comment by marcogargano** [comment]
Ciao @angelavit 
per come sono stati realizzati i [modelli di riferimento](https://italia.github.io/design-comuni-prototipi/it/kit.html#template-html), quel menu su mobile scompare. 
Il consiglio che ti posso dare, è quello di ripetere i social nel footer.
