### ISSUE TITLE
Installazione template Wordpress

### ISSUE THREAD

**Issue by monicacarlino** [italia/design-wordpress-theme#77]
Sto provando ad installare il template di Design Italia, alla pagina https://github.com/italia/design-wordpress-theme.
Ho seguito tutte le indicazioni, ma sono alle prime armi con WP e non sono riuscita a visualizzare la demo completa (quella in verde, per intenderci), ma solo header e footer in blu e qualche fascia diversa dalla demo. 
Qui il sito di test: https://ecommerce.clio.it/home-page/
La domanda è: è normale che sia così? Pensavo avrei trovato le fasce di esempio, in modo da iniziare a capirne il funzionamento.
Grazie.

**Comment by marcogargano** [comment]
Ciao @monicacarlino 
per riprodurre la demo bisogna installare [Page Builder by SiteOrigin](https://wordpress.org/plugins/siteorigin-panels/) e seguire le istruzioni [qui](https://github.com/italia/design-wordpress-theme#come-importare-il-template). 
Altrimenti puoi creare le pagine con qualunque altro builder.
