### ISSUE TITLE
Importare nuovatvdigitale.mise.gov.it

### ISSUE THREAD

**Issue by CloudItaly** [italia/design-wordpress-theme#78]
Salve a tutti. 
E' possibile ottenere il file *.json che possa permettermi di ottenere un template quanto più vicino a questo qui?

**Comment by marcogargano** [comment]
Ciao @CloudItaly 
il file e le istruzioni per riprodurre la homepage le puoi trovare qui: 
[https://github.com/italia/design-wordpress-theme#come-importare-il-template](https://github.com/italia/design-wordpress-theme#come-importare-il-template)
