### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by giancarlobuzzanca** [italia/design-wordpress-theme#8]
Ho visto dalla demo del tema,  http://design-italia.marcogargano.com/ , che c'è la possibilità di introdurre una sidebar sulle pagine.
Puoi dirmi come fare? Inserisco widget nella sidebar ma non riesco a visualizzare nulla. Tieni conto che nella schermata di costruzione della pagina, alla sezione Attributi ho impostato "template standard". D'altra parte nella personalizzazione del tema non riesco a trovare una voce di scelte del layout.
Spero di non essere stato troppo fumoso.
Grazie in anticipo.
Giancarlo

**Comment by marcogargano** [comment]
Ciao @giancarlobuzzanca 
non c'era ancora la possibilità, ora ho aggiunto il template con la sidebar per le pagine.
Ho da poco fatto un aggiornamento del tema, dovresti trovarlo tra gli Aggiornamenti in WP.
Tra l'altro stavo pensando anche di aggiungere un'area widget dedicata alle pagine, per personalizzarla rispetto a quella dei post... dopo lo faccio.
Fammi sapere se ti compare nel Modifica pagina, sotto Attributi della pagina > Modello > Pagina con sidebar

**Comment by marcmajan** [comment]
A tutt’oggi l’aggiornamento del tema non è ancora disponibile su WP. Volevo saper se già supporta i js. Sto testando il tema per un istituto scolastico di secondo grado ma non volevo usare page builder, preferendo testare le effettive potenzialità che avrà il tema man mano che viene sviluppato.

**Comment by marcogargano** [comment]
Ciao @marcmajan ,
ho riscontrato alcuni problemi con gli aggiornamenti del tema, ora con l'ultimo rilascio dovrei aver sistemato. Fammi sapere se ci sono problemi.
Inoltre ora il tema integra jQuery e le librerie di [Bootstrap Italia](https://italia.github.io/bootstrap-italia/).

**Comment by marcmajan** [comment]
@marcogargano ,
Ancora mi risulta non sia possibile aggiornare il tema dall’interno di WP, rimane la versione 0.1

**Comment by marcogargano** [comment]
Cavolo... la versione 0.1 era proprio la primissima.
Ti consiglierei di [riscaricare lo zip](https://raw.githubusercontent.com/italia/design-wordpress-theme/master/design-italia.zip) e reinstallare il tema, i contenuti non andranno persi.

**Comment by marcmajan** [comment]
Rilevo un malfunzionamento nella creazione della pagina articoli (versione 0.6)

**Comment by marcogargano** [comment]
Che tipo di malfunzionamento? Grazie!

**Comment by marcmajan** [comment]
@marcogargano 
Invio il link https://isaurb.altervista.org/blog  al test. La pagina “eventi” è quella che dovrebbe contenere gli articoli.

**Comment by marcogargano** [comment]
@marcmajan 
Ma la pagina "eventi" utilizza il template della home page (quella su sfondo grigio è l'area widget dedicata alla homepage). 
Per avere una lista di articoli sarebbe meglio il template archive, e quindi dovresti gestire gli eventi come categoria e all'interno i suoi articoli.

**Comment by marcmajan** [comment]
@marcogargano 
Il fatto è che la pagina “eventi” non usa affatto il template della home page, per questo ho parlato di malfunzionamento

**Comment by marcogargano** [comment]
@marcmajan 
Ho controllato meglio il codice e sembra non prenda alcun modello. Non capisco il perché... 
Mi controlleresti una cosa?! In Wordpress, nel "Modifica pagina" della pagina Eventi è selezionato un modello in "Attributi della pagina"?

**Comment by marcmajan** [comment]
@marcogargano 
Nel box WP  “Attributi della pagina”  della pagina contenente gli articoli non è presente il dropdown button per la scelta del modello

**Comment by marcogargano** [comment]
@marcmajan
Non capisco... è una pagina o un post?
Di solito le pagine che contengono liste di post sono archivi o categorie, ma non le vedi nel CMS.
Se non riesco a capire la situazione in cui sei, mi riesce difficile aiutarti.
La pagina in questione è questa: [http://isaurb.altervista.org/blog/eventi/](http://isaurb.altervista.org/blog/eventi/) ...giusto?
Ho notato nel codice questa classe *"av-theme-design-italia"*, tu sai a cosa si riferisce, io non l'ho usata.

**Comment by marcmajan** [comment]
@marcogargano 
Riassumo: 
l’obiettivo del mio test consiste nel mettermi nel ruolo dell’utilizzatore comune, verificando le potenzialità d’uso del tema per specifiche istituzioni. Da questa premessa anche la decisione di limitare al minimo i plugins specie quelli troppo invasivi. 
Nello specifico ho deciso di utilizzare, come spesso succede, come homepage una pagina statica e utilizzare come pagina contenente i post una pagina chiamata in questo caso “eventi”. (Procedura che personalmente ho usato con numerosi siti WP che ho avuto modo di sviluppare e gestire).
Il problema che ho riscontrato è che il tema non genera in “eventi” una pagina di archivio e lista dei post di tutte le categorie (come ci si aspetta). Genera quello che hai visto nel link che ho inviato e mi sono permesso di segnalarti come, a mio modesto avviso, un malfunzionamento.
Sempre in considerazione della premessa che ho fatto non ho minimamente toccato i codici del tema.

**Comment by marcogargano** [comment]
Ok... ora ho capito 😊
Si rompe quando imposti la pagina come Pagina Articoli nelle Impostazioni Home.
Grazie mille... hai trovato un bug 👍
Nei prossimi giorni lo sistemo!

**Comment by marcmajan** [comment]
Ciao @marcogargano 
Ti segnalo che (versione 0.8) creando pagina statica con modello home page, questa presenta intestazione tipica dei post: filetto hr di separazione, titolo-link, data... Non ci dovrebbe essere.
Permane il bug nell’impostazione della pagina articoli.
Saluti!

**Comment by marcogargano** [comment]
@marcmajan grazie mille per i tuoi feedback; anche il tuo link mi è molto prezioso per capire come si comporta il tema su un altro sito che non sia il mio 😁

Sicuramente un bug relativo alle immagini persiste e quello lo fixo facilmente. 
Però volevo capire con te quale possa essere la miglior soluzione per questa pagina. Io personalmente non uso molto questo tipo di pagina e quindi vorrei capire con te quale possa essere una soluzione ideale.

Ho guardato i classici temi pre-installati (Twenty Fifteen, Twenty Fifteen, ...) e quel tipo di pagina assomiglia a una pagina archivio.
Mi dicevi che hr di separazione, titolo-link e data non ci dovrebbero essere, ma quindi lascio solo il titolo e sotto il contenuto?
Dimmi pure come vorresti vederla e la facciamo... grazie!

**Comment by marcmajan** [comment]
@marcogargano 
Mi fa piacere esserti in qualche modo utile nel grande lavoro che stai portando avanti.
Riguardo alla pagina è proprio come vedi nella maggioranza di siti WP: avere una pagina archivio dove sono inseriti gli articoli di tutte le categorie. Finora una simile pagina, come hai constatato anche tu, non è possibile crearla.

**Comment by marcogargano** [comment]
Ciao @marcmajan , ho fatto un aggiornamento, il problema dovrebbe esser risolto.
Inoltre ho aggiunto un widget secondo me molto interessante.
Fammi sapere se ti piace 😁

**Comment by marcmajan** [comment]
Ciao @marcogargano 
Bel lavoro, la cosa si arricchisce....Ho comunque notato:
- nella pagina archivio degli articoli non è possibile inserire sidebar
- nel widget mansory (inserito attraverso Page builder) i link ai post determinano una 404

**Comment by marcogargano** [comment]
Grazie @marcmajan 
I link nel widget ho visto ed è un'errore stupido, lo correggo facile.
Per "pagina archivio degli articoli" intendi sempre quella a cui ci riferivamo prima?!
Quindi renderla una vera e propria pagina archivio...
