### ISSUE TITLE
JS Bootstrap italia 

### ISSUE THREAD

**Issue by andycolo78** [italia/design-wordpress-theme#81]
Ciao @marcogargano 
l'enqueue degli script JS di bootstrap italia è stato tolto dalla versione 0.13
C'è un motivo particolare per questo?

Grazie

**Comment by marcogargano** [comment]
Ciao @andycolo78 
perdona il ritardo nella risposta. 
Gli script JS sono stati rimossi per evitare conflitti con altri script riscontrati da alcuni utenti. 
Grazie a te!
