### ISSUE TITLE
Didascalia Immagine in evidenza

### ISSUE THREAD

**Issue by angelavit** [italia/design-wordpress-theme#82]
Ciao,
è possibile visualizzare la didascalia delle immagini in evidenza impostate per le pagine?
Inserendo l'immagine direttamente nell'articolo viene mostrata la didascalia, cosa che non accade per l'immagine in evidenza.
Sto cercando un modo per mostrare licenza e autore delle immagini, qualcuno mi sa aiutare?
grazie

**Comment by marcogargano** [comment]
Ciao @angelavit 
nel template per post "DI - Articolo con sidebar", c'è la possibilità di inserire la Didascalia per l'immagine in evidenza;  comparirà sotto l'immagine.
