### ISSUE TITLE
Apertura tendina menu con evento click oltre mouseover (label: proposal)

### ISSUE THREAD

**Issue by alfredocentinaro** [italia/design-wordpress-theme#83]
Sarebbe bello poter selezionare da backend la modalità dell'apertura del menù principale sia col semplice mouseover, come standard attuale, che con il click del mouse sul menu scelto.

**Comment by marcogargano** [comment]
Ciao @alfredocentinaro 
perdona il ritardo nella risposta. 
Al momento questo comportamento non è previsto ma è possibile estendere facilmente il tema con un tema figlio e sviluppare il comportamento atteso. 
Grazie
