### ISSUE TITLE
Personalizzazione colore primario template wordpress 

### ISSUE THREAD

**Issue by giuseppetucci** [italia/design-wordpress-theme#89]
Sarebbe possibile inserire un campo per modificare il colore primario del template “modello comuni”?

Grazie

**Comment by giuseppetucci** [comment]
Grazie Marco, ma questa possibilità non è possibile nel nuovo template modello comuni.

**Comment by MarcoGargano** [comment]
Non credo di aver capito. 
[Qui](https://www.marcogargano.com/wp-pa/wp/?p=1484) trovi un video con le indicazioni per modificare i colori; quali colori in particolare vorresti modificare?

**Comment by giuseppetucci** [comment]
Il template di cui parlo è questo https://designers.italia.it/modello/comuni/
In effetti sul template da te proposto è molto più semplice la modifica dei colori del template.
